### PR TITLE
Add dropdown to additionally filter by language

### PR DESCRIPTION
**Pull request by vinmaster**

### CODE REVIEW

**Comment by vinmaster** [comment]
This is for issue: https://github.com/ivanseed/gitstats/issues/3

**Comment by ivanseed** [comment]
Hey, thanks for the PR it works perfectly!

If you don't mind - could you perhaps move the drop down to be on the same line as the search bar and styled similarly? If not I can create a separate issue for the styling of this feature.

**Comment by vinmaster** [comment]
I've made some changes. I tried what I can to match size, background, and foreground. Please review 😄

**Comment by ivanseed** [comment]
Not sure why this issue did not auto close, but your changes have been merged in, thanks!

**Pull request closed without merging**
